### PR TITLE
Update leaflet to 1.3.1 & add some methods/types

### PR DESCRIPTION
**Pull request by damercier**
Update to leaflet 1.3.1 & adapt the façade to have more methods/types available.

### CODE REVIEW

**Comment by damercier** [comment]
Thanks for your feedback. I've updated the Pull Request with the webjar ;-)

**Comment by chrisshafer** [comment]
Thanks!

**Comment by damercier** [comment]
Thank you for merging my PR. Is it possible to have a release with those changes ?

**Comment by chrisshafer** [comment]
Hey @damercier just released v1.04, sorry it took a while to get that out, the leaflet-draw module had a dependency conflict with the leaflet-facade that had to be resolved.

**Pull request merged**
